/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './ngx-agile-slider.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/http';
import * as import4 from './services/lazy-loader.service';
class NgxAgileSliderModuleInjector extends import0.ɵNgModuleInjector<import1.NgxAgileSliderModule> {
  _CommonModule_0:import2.CommonModule;
  _HttpModule_1:import3.HttpModule;
  _NgxAgileSliderModule_2:import1.NgxAgileSliderModule;
  __NgLocalization_3:import2.NgLocaleLocalization;
  __BrowserXhr_4:import3.BrowserXhr;
  __ResponseOptions_5:import3.BaseResponseOptions;
  __XSRFStrategy_6:any;
  __XHRBackend_7:import3.XHRBackend;
  __RequestOptions_8:import3.BaseRequestOptions;
  __Http_9:any;
  __LazyLoaderService_10:import4.LazyLoaderService;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_3():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_3 == null)) { (this.__NgLocalization_3 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_3;
  }
  get _BrowserXhr_4():import3.BrowserXhr {
    if ((this.__BrowserXhr_4 == null)) { (this.__BrowserXhr_4 = new import3.BrowserXhr()); }
    return this.__BrowserXhr_4;
  }
  get _ResponseOptions_5():import3.BaseResponseOptions {
    if ((this.__ResponseOptions_5 == null)) { (this.__ResponseOptions_5 = new import3.BaseResponseOptions()); }
    return this.__ResponseOptions_5;
  }
  get _XSRFStrategy_6():any {
    if ((this.__XSRFStrategy_6 == null)) { (this.__XSRFStrategy_6 = import3.ɵb()); }
    return this.__XSRFStrategy_6;
  }
  get _XHRBackend_7():import3.XHRBackend {
    if ((this.__XHRBackend_7 == null)) { (this.__XHRBackend_7 = new import3.XHRBackend(this._BrowserXhr_4,this._ResponseOptions_5,this._XSRFStrategy_6)); }
    return this.__XHRBackend_7;
  }
  get _RequestOptions_8():import3.BaseRequestOptions {
    if ((this.__RequestOptions_8 == null)) { (this.__RequestOptions_8 = new import3.BaseRequestOptions()); }
    return this.__RequestOptions_8;
  }
  get _Http_9():any {
    if ((this.__Http_9 == null)) { (this.__Http_9 = import3.ɵc(this._XHRBackend_7,this._RequestOptions_8)); }
    return this.__Http_9;
  }
  get _LazyLoaderService_10():import4.LazyLoaderService {
    if ((this.__LazyLoaderService_10 == null)) { (this.__LazyLoaderService_10 = new import4.LazyLoaderService(this._Http_9)); }
    return this.__LazyLoaderService_10;
  }
  createInternal():import1.NgxAgileSliderModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._HttpModule_1 = new import3.HttpModule();
    this._NgxAgileSliderModule_2 = new import1.NgxAgileSliderModule();
    return this._NgxAgileSliderModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.HttpModule)) { return this._HttpModule_1; }
    if ((token === import1.NgxAgileSliderModule)) { return this._NgxAgileSliderModule_2; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_3; }
    if ((token === import3.BrowserXhr)) { return this._BrowserXhr_4; }
    if ((token === import3.ResponseOptions)) { return this._ResponseOptions_5; }
    if ((token === import3.XSRFStrategy)) { return this._XSRFStrategy_6; }
    if ((token === import3.XHRBackend)) { return this._XHRBackend_7; }
    if ((token === import3.RequestOptions)) { return this._RequestOptions_8; }
    if ((token === import3.Http)) { return this._Http_9; }
    if ((token === import4.LazyLoaderService)) { return this._LazyLoaderService_10; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const NgxAgileSliderModuleNgFactory:import0.NgModuleFactory<import1.NgxAgileSliderModule> = new import0.NgModuleFactory<any>(NgxAgileSliderModuleInjector,import1.NgxAgileSliderModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL21udC9oZDIvd29yay9wcm9qZWN0cy9wcml2YXRlL25neC1hZ2lsZS1zbGlkZXIvc3JjL2FwcC9jYXJvdXNlbC9uZ3gtYWdpbGUtc2xpZGVyLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9tbnQvaGQyL3dvcmsvcHJvamVjdHMvcHJpdmF0ZS9uZ3gtYWdpbGUtc2xpZGVyL3NyYy9hcHAvY2Fyb3VzZWwvbmd4LWFnaWxlLXNsaWRlci5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
