/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './ngx-agile-slider-item.component';
const styles_SliderItemComponent:any[] = ([] as any[]);
export const RenderType_SliderItemComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_SliderItemComponent,
  data: {}
}
);
export function View_SliderItemComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵqud(201326592,1,{sliderItem: 0}),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,[
      [
        1,
        0
      ]
      ,
      [
        'sliderItem',
        1
      ]

    ]
      ,(null as any),3,'li',[[
        'class',
        'ngx-agile-slider-item variablewidth'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n      '])),
    import0.ɵncd((null as any),0),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(null as any),(null as any));
}
function View_SliderItemComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ngx-agile-slider-item',([] as any[]),(null as any),(null as any),(null as any),View_SliderItemComponent_0,RenderType_SliderItemComponent)),
    import0.ɵdid(2121728,(null as any),0,import1.SliderItemComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const SliderItemComponentNgFactory:import0.ComponentFactory<import1.SliderItemComponent> = import0.ɵccf('ngx-agile-slider-item',import1.SliderItemComponent,View_SliderItemComponent_Host_0,{
  additionalClasses: 'additionalClasses',
  width: 'width'
}
,{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL21udC9oZDIvd29yay9wcm9qZWN0cy9wcml2YXRlL25neC1hZ2lsZS1zbGlkZXIvc3JjL2FwcC9jYXJvdXNlbC9jb21wb25lbnRzL25neC1hZ2lsZS1zbGlkZXItaXRlbS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vbW50L2hkMi93b3JrL3Byb2plY3RzL3ByaXZhdGUvbmd4LWFnaWxlLXNsaWRlci9zcmMvYXBwL2Nhcm91c2VsL2NvbXBvbmVudHMvbmd4LWFnaWxlLXNsaWRlci1pdGVtLmNvbXBvbmVudC50cyIsIm5nOi8vL21udC9oZDIvd29yay9wcm9qZWN0cy9wcml2YXRlL25neC1hZ2lsZS1zbGlkZXIvc3JjL2FwcC9jYXJvdXNlbC9jb21wb25lbnRzL25neC1hZ2lsZS1zbGlkZXItaXRlbS5jb21wb25lbnQudHMuU2xpZGVySXRlbUNvbXBvbmVudC5odG1sIiwibmc6Ly8vbW50L2hkMi93b3JrL3Byb2plY3RzL3ByaXZhdGUvbmd4LWFnaWxlLXNsaWRlci9zcmMvYXBwL2Nhcm91c2VsL2NvbXBvbmVudHMvbmd4LWFnaWxlLXNsaWRlci1pdGVtLmNvbXBvbmVudC50cy5TbGlkZXJJdGVtQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgPGxpICNzbGlkZXJJdGVtIGNsYXNzPVwibmd4LWFnaWxlLXNsaWRlci1pdGVtIHZhcmlhYmxld2lkdGhcIj5cbiAgICAgIDxuZy1jb250ZW50PjwvbmctY29udGVudD5cbiAgICA8L2xpPlxuICAiLCI8bmd4LWFnaWxlLXNsaWRlci1pdGVtPjwvbmd4LWFnaWxlLXNsaWRlci1pdGVtPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7SUFDSTtNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUE0RDtnQkFDMUQ7SUFBeUI7SUFDdEI7Ozs7OztJQ0hUO2dCQUFBOzs7Ozs7OzsifQ==
